### ISSUE TITLE
Content type fields updates needed

### ISSUE THREAD

**Issue by oklmnk** [dsai-git/dsai-drupal#1]
Need to add these single-line text fields (and image fields)

Courses:

1. Rename "Courses" field to "Course Title"
2. Add course length field
3. Add course date
4. Add venue
5. Add an image (same as in the article)

Events:

1. Rename "Title" to "Event Title"
2. Add "Event Date"
3. Add "Venue"
4. Add Image
5. Remove "event category" dropdown, we can automate this with views. We use view filters for this: https://drupal.stackexchange.com/questions/273088/views-filter-criteria-date-field-is-greater-than-current-date
6. Add event URL (link to eventbrite or whatever)
7. Add event teaser text. Limit this to 140 characters. A shortened description mandatory to fill. We should have this, otherwise, we'll always have to ask for a shorter description.

Speakers:

1. Add image
2. Rename "Speakers" to speaker name
3. Rename Body to "Bio" if possible
4. Add linkedin, twitter, website, and youtube link fields

Team:

Same field updates as speakers.

**Comment by mahajan-dsai** [comment]
Fields created/updated; need checking.
Some field names/labels will change as they are reviewed.

**Comment by mahajan-dsai** [comment]
Updated all items in the list, with differences in names to identify each 'field name'.
