### ISSUE TITLE
Please convert the event teaser to full-text multiline editor and move the field below the title.

### ISSUE THREAD

**Issue by ghost** [dsai-git/dsai-drupal#3]
Please convert the event teaser to full-text multiline editor and move the field below the title.

![Screenshot from 2019-12-05 21-31-37](https://user-images.githubusercontent.com/47801537/70227415-a8aad780-17a6-11ea-8446-f30bc3c8df52.png)

_Originally posted by @oklmnk in https://github.com/dsai-git/dsai-drupal/pull/2/review_comment/create_

**Comment by mahajan-dsai** [comment]
Please review
