### ISSUE TITLE
Improve configuration of text editors across all pages

### ISSUE THREAD

**Issue by ghost** [dsai-git/dsai-drupal#8]
Convert these to single-line text editors with no help or text format selector:
- course date
- course length
- course price
- event date
- event venue
- job title
- location
- date posted
- company name
- industry
- entry level
- job duration
- min education
- min experience
- required travel
- salary
- date close
- speaker name

Convert this to freeform text field not internal URL selector, since we want to enter URL to outside resources:
- event URL
- speaker linkedin
- speaker twitter
- speaker website
- speaker youtube
- team linkedin
- team twitter
- team website
- team youtube

Convert this to multiline full-text editor:
- event teaser
-  speaker bio
- team member bio

**Comment by mahajan-dsai** [comment]
Not entirely sure what is being requested for the first block of fields - plain text?
The URL field appears to allow the entry of internal and external links - so, leaving as is
Full text fields changed
